// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: proto/gossip_rpc_chunk.proto

package gossip_rpc_chunk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckStatus int32

const (
	AckStatus_ACK_UNKNOWN   AckStatus = 0 // 保留
	AckStatus_ACK_OK        AckStatus = 1 // 正常收到
	AckStatus_ACK_DUPLICATE AckStatus = 2 // 已收到过（去重命中）
	AckStatus_ACK_COMPLETE  AckStatus = 3 // 所有 chunk 接收完成
	AckStatus_ACK_REJECT    AckStatus = 4 // 拒绝接收（资源/策略）
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK_UNKNOWN",
		1: "ACK_OK",
		2: "ACK_DUPLICATE",
		3: "ACK_COMPLETE",
		4: "ACK_REJECT",
	}
	AckStatus_value = map[string]int32{
		"ACK_UNKNOWN":   0,
		"ACK_OK":        1,
		"ACK_DUPLICATE": 2,
		"ACK_COMPLETE":  3,
		"ACK_REJECT":    4,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gossip_rpc_chunk_proto_enumTypes[0].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_proto_gossip_rpc_chunk_proto_enumTypes[0]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_gossip_rpc_chunk_proto_rawDescGZIP(), []int{0}
}

// 分块消息
type GossipChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原始消息的哈希值（不是分片的哈希值）
	PayloadHash string `protobuf:"bytes,1,opt,name=PayloadHash,proto3" json:"PayloadHash,omitempty"`
	// 发送者的哈希值
	SenderHash string `protobuf:"bytes,2,opt,name=SenderHash,proto3" json:"SenderHash,omitempty"`
	// 发送的次数
	SessionID int32 `protobuf:"varint,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	// 分片数据
	ChunkData []byte `protobuf:"bytes,4,opt,name=ChunkData,proto3" json:"ChunkData,omitempty"`
	// 分片索引
	ChunkIndex int32 `protobuf:"varint,5,opt,name=ChunkIndex,proto3" json:"ChunkIndex,omitempty"`
	// 总分片数
	TotalChunks   int32 `protobuf:"varint,6,opt,name=TotalChunks,proto3" json:"TotalChunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipChunk) Reset() {
	*x = GossipChunk{}
	mi := &file_proto_gossip_rpc_chunk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipChunk) ProtoMessage() {}

func (x *GossipChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_rpc_chunk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipChunk.ProtoReflect.Descriptor instead.
func (*GossipChunk) Descriptor() ([]byte, []int) {
	return file_proto_gossip_rpc_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *GossipChunk) GetPayloadHash() string {
	if x != nil {
		return x.PayloadHash
	}
	return ""
}

func (x *GossipChunk) GetSenderHash() string {
	if x != nil {
		return x.SenderHash
	}
	return ""
}

func (x *GossipChunk) GetSessionID() int32 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *GossipChunk) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *GossipChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *GossipChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

type GossipChunkAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原始消息的哈希值（不是分片的哈希值）
	PayloadHash string `protobuf:"bytes,1,opt,name=PayloadHash,proto3" json:"PayloadHash,omitempty"`
	// 接收者的哈希值
	RecvHash string `protobuf:"bytes,2,opt,name=RecvHash,proto3" json:"RecvHash,omitempty"`
	// 发送的次数
	SessionID int32 `protobuf:"varint,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	// 确认的分片索引
	ChunkIndex int32 `protobuf:"varint,4,opt,name=ChunkIndex,proto3" json:"ChunkIndex,omitempty"`
	// 接收状态
	Status        AckStatus `protobuf:"varint,5,opt,name=Status,proto3,enum=gossip_rpc_chunk.AckStatus" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipChunkAck) Reset() {
	*x = GossipChunkAck{}
	mi := &file_proto_gossip_rpc_chunk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipChunkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipChunkAck) ProtoMessage() {}

func (x *GossipChunkAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_rpc_chunk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipChunkAck.ProtoReflect.Descriptor instead.
func (*GossipChunkAck) Descriptor() ([]byte, []int) {
	return file_proto_gossip_rpc_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *GossipChunkAck) GetPayloadHash() string {
	if x != nil {
		return x.PayloadHash
	}
	return ""
}

func (x *GossipChunkAck) GetRecvHash() string {
	if x != nil {
		return x.RecvHash
	}
	return ""
}

func (x *GossipChunkAck) GetSessionID() int32 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *GossipChunkAck) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *GossipChunkAck) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK_UNKNOWN
}

var File_proto_gossip_rpc_chunk_proto protoreflect.FileDescriptor

const file_proto_gossip_rpc_chunk_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/gossip_rpc_chunk.proto\x12\x10gossip_rpc_chunk\x1a\x1bgoogle/protobuf/empty.proto\"\xcd\x01\n" +
	"\vGossipChunk\x12 \n" +
	"\vPayloadHash\x18\x01 \x01(\tR\vPayloadHash\x12\x1e\n" +
	"\n" +
	"SenderHash\x18\x02 \x01(\tR\n" +
	"SenderHash\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\x05R\tsessionID\x12\x1c\n" +
	"\tChunkData\x18\x04 \x01(\fR\tChunkData\x12\x1e\n" +
	"\n" +
	"ChunkIndex\x18\x05 \x01(\x05R\n" +
	"ChunkIndex\x12 \n" +
	"\vTotalChunks\x18\x06 \x01(\x05R\vTotalChunks\"\xc1\x01\n" +
	"\x0eGossipChunkAck\x12 \n" +
	"\vPayloadHash\x18\x01 \x01(\tR\vPayloadHash\x12\x1a\n" +
	"\bRecvHash\x18\x02 \x01(\tR\bRecvHash\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\x05R\tsessionID\x12\x1e\n" +
	"\n" +
	"ChunkIndex\x18\x04 \x01(\x05R\n" +
	"ChunkIndex\x123\n" +
	"\x06Status\x18\x05 \x01(\x0e2\x1b.gossip_rpc_chunk.AckStatusR\x06Status*]\n" +
	"\tAckStatus\x12\x0f\n" +
	"\vACK_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ACK_OK\x10\x01\x12\x11\n" +
	"\rACK_DUPLICATE\x10\x02\x12\x10\n" +
	"\fACK_COMPLETE\x10\x03\x12\x0e\n" +
	"\n" +
	"ACK_REJECT\x10\x042g\n" +
	"\x12GossipChunkService\x12Q\n" +
	"\n" +
	"PushChunks\x12\x1d.gossip_rpc_chunk.GossipChunk\x1a .gossip_rpc_chunk.GossipChunkAck(\x010\x01B:Z8github.com/sukasukasuka123/Gossip/proto/gossip_rpc_chunkb\x06proto3"

var (
	file_proto_gossip_rpc_chunk_proto_rawDescOnce sync.Once
	file_proto_gossip_rpc_chunk_proto_rawDescData []byte
)

func file_proto_gossip_rpc_chunk_proto_rawDescGZIP() []byte {
	file_proto_gossip_rpc_chunk_proto_rawDescOnce.Do(func() {
		file_proto_gossip_rpc_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gossip_rpc_chunk_proto_rawDesc), len(file_proto_gossip_rpc_chunk_proto_rawDesc)))
	})
	return file_proto_gossip_rpc_chunk_proto_rawDescData
}

var file_proto_gossip_rpc_chunk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_gossip_rpc_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gossip_rpc_chunk_proto_goTypes = []any{
	(AckStatus)(0),         // 0: gossip_rpc_chunk.AckStatus
	(*GossipChunk)(nil),    // 1: gossip_rpc_chunk.GossipChunk
	(*GossipChunkAck)(nil), // 2: gossip_rpc_chunk.GossipChunkAck
}
var file_proto_gossip_rpc_chunk_proto_depIdxs = []int32{
	0, // 0: gossip_rpc_chunk.GossipChunkAck.Status:type_name -> gossip_rpc_chunk.AckStatus
	1, // 1: gossip_rpc_chunk.GossipChunkService.PushChunks:input_type -> gossip_rpc_chunk.GossipChunk
	2, // 2: gossip_rpc_chunk.GossipChunkService.PushChunks:output_type -> gossip_rpc_chunk.GossipChunkAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gossip_rpc_chunk_proto_init() }
func file_proto_gossip_rpc_chunk_proto_init() {
	if File_proto_gossip_rpc_chunk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gossip_rpc_chunk_proto_rawDesc), len(file_proto_gossip_rpc_chunk_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gossip_rpc_chunk_proto_goTypes,
		DependencyIndexes: file_proto_gossip_rpc_chunk_proto_depIdxs,
		EnumInfos:         file_proto_gossip_rpc_chunk_proto_enumTypes,
		MessageInfos:      file_proto_gossip_rpc_chunk_proto_msgTypes,
	}.Build()
	File_proto_gossip_rpc_chunk_proto = out.File
	file_proto_gossip_rpc_chunk_proto_goTypes = nil
	file_proto_gossip_rpc_chunk_proto_depIdxs = nil
}
