// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.26.1
// source: proto/gossip_rpc_chunk.proto

package gossip_rpc_chunk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GossipChunkService_PushChunks_FullMethodName = "/gossip_rpc_chunk.GossipChunkService/PushChunks"
)

// GossipChunkServiceClient is the client API for GossipChunkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GossipChunkServiceClient interface {
	// 分块消息流
	PushChunks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipChunk, GossipChunkAck], error)
}

type gossipChunkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGossipChunkServiceClient(cc grpc.ClientConnInterface) GossipChunkServiceClient {
	return &gossipChunkServiceClient{cc}
}

func (c *gossipChunkServiceClient) PushChunks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipChunk, GossipChunkAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GossipChunkService_ServiceDesc.Streams[0], GossipChunkService_PushChunks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GossipChunk, GossipChunkAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GossipChunkService_PushChunksClient = grpc.BidiStreamingClient[GossipChunk, GossipChunkAck]

// GossipChunkServiceServer is the server API for GossipChunkService service.
// All implementations must embed UnimplementedGossipChunkServiceServer
// for forward compatibility.
type GossipChunkServiceServer interface {
	// 分块消息流
	PushChunks(grpc.BidiStreamingServer[GossipChunk, GossipChunkAck]) error
	mustEmbedUnimplementedGossipChunkServiceServer()
}

// UnimplementedGossipChunkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGossipChunkServiceServer struct{}

func (UnimplementedGossipChunkServiceServer) PushChunks(grpc.BidiStreamingServer[GossipChunk, GossipChunkAck]) error {
	return status.Error(codes.Unimplemented, "method PushChunks not implemented")
}
func (UnimplementedGossipChunkServiceServer) mustEmbedUnimplementedGossipChunkServiceServer() {}
func (UnimplementedGossipChunkServiceServer) testEmbeddedByValue()                            {}

// UnsafeGossipChunkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GossipChunkServiceServer will
// result in compilation errors.
type UnsafeGossipChunkServiceServer interface {
	mustEmbedUnimplementedGossipChunkServiceServer()
}

func RegisterGossipChunkServiceServer(s grpc.ServiceRegistrar, srv GossipChunkServiceServer) {
	// If the following call panics, it indicates UnimplementedGossipChunkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GossipChunkService_ServiceDesc, srv)
}

func _GossipChunkService_PushChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GossipChunkServiceServer).PushChunks(&grpc.GenericServerStream[GossipChunk, GossipChunkAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GossipChunkService_PushChunksServer = grpc.BidiStreamingServer[GossipChunk, GossipChunkAck]

// GossipChunkService_ServiceDesc is the grpc.ServiceDesc for GossipChunkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GossipChunkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gossip_rpc_chunk.GossipChunkService",
	HandlerType: (*GossipChunkServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushChunks",
			Handler:       _GossipChunkService_PushChunks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gossip_rpc_chunk.proto",
}
