// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.26.1
// source: proto/gossip_rpc.proto

package gossip_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gossip_PushMessage_FullMethodName   = "/gossip_rpc.Gossip/PushMessage"
	Gossip_SubscribeAcks_FullMethodName = "/gossip_rpc.Gossip/SubscribeAcks"
	Gossip_Stream_FullMethodName        = "/gossip_rpc.Gossip/Stream"
)

// GossipClient is the client API for Gossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GossipClient interface {
	// 解耦模式
	// 客户端向对端推送消息（client-stream）
	PushMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GossipMessage, emptypb.Empty], error)
	// 客户端订阅来自对端的 ACK
	SubscribeAcks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GossipACK], error)
	// 双向流模式
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipMessage, GossipACK], error)
}

type gossipClient struct {
	cc grpc.ClientConnInterface
}

func NewGossipClient(cc grpc.ClientConnInterface) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) PushMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GossipMessage, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gossip_ServiceDesc.Streams[0], Gossip_PushMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GossipMessage, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_PushMessageClient = grpc.ClientStreamingClient[GossipMessage, emptypb.Empty]

func (c *gossipClient) SubscribeAcks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GossipACK], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gossip_ServiceDesc.Streams[1], Gossip_SubscribeAcks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, GossipACK]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_SubscribeAcksClient = grpc.ServerStreamingClient[GossipACK]

func (c *gossipClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipMessage, GossipACK], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gossip_ServiceDesc.Streams[2], Gossip_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GossipMessage, GossipACK]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_StreamClient = grpc.BidiStreamingClient[GossipMessage, GossipACK]

// GossipServer is the server API for Gossip service.
// All implementations must embed UnimplementedGossipServer
// for forward compatibility.
type GossipServer interface {
	// 解耦模式
	// 客户端向对端推送消息（client-stream）
	PushMessage(grpc.ClientStreamingServer[GossipMessage, emptypb.Empty]) error
	// 客户端订阅来自对端的 ACK
	SubscribeAcks(*emptypb.Empty, grpc.ServerStreamingServer[GossipACK]) error
	// 双向流模式
	Stream(grpc.BidiStreamingServer[GossipMessage, GossipACK]) error
	mustEmbedUnimplementedGossipServer()
}

// UnimplementedGossipServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGossipServer struct{}

func (UnimplementedGossipServer) PushMessage(grpc.ClientStreamingServer[GossipMessage, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method PushMessage not implemented")
}
func (UnimplementedGossipServer) SubscribeAcks(*emptypb.Empty, grpc.ServerStreamingServer[GossipACK]) error {
	return status.Error(codes.Unimplemented, "method SubscribeAcks not implemented")
}
func (UnimplementedGossipServer) Stream(grpc.BidiStreamingServer[GossipMessage, GossipACK]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGossipServer) mustEmbedUnimplementedGossipServer() {}
func (UnimplementedGossipServer) testEmbeddedByValue()                {}

// UnsafeGossipServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GossipServer will
// result in compilation errors.
type UnsafeGossipServer interface {
	mustEmbedUnimplementedGossipServer()
}

func RegisterGossipServer(s grpc.ServiceRegistrar, srv GossipServer) {
	// If the following call panics, it indicates UnimplementedGossipServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gossip_ServiceDesc, srv)
}

func _Gossip_PushMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GossipServer).PushMessage(&grpc.GenericServerStream[GossipMessage, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_PushMessageServer = grpc.ClientStreamingServer[GossipMessage, emptypb.Empty]

func _Gossip_SubscribeAcks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GossipServer).SubscribeAcks(m, &grpc.GenericServerStream[emptypb.Empty, GossipACK]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_SubscribeAcksServer = grpc.ServerStreamingServer[GossipACK]

func _Gossip_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GossipServer).Stream(&grpc.GenericServerStream[GossipMessage, GossipACK]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_StreamServer = grpc.BidiStreamingServer[GossipMessage, GossipACK]

// Gossip_ServiceDesc is the grpc.ServiceDesc for Gossip service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gossip_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gossip_rpc.Gossip",
	HandlerType: (*GossipServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushMessage",
			Handler:       _Gossip_PushMessage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeAcks",
			Handler:       _Gossip_SubscribeAcks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stream",
			Handler:       _Gossip_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gossip_rpc.proto",
}
