// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.26.1
// source: proto/gossip_rpc.proto

package gossip_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gossip_MessageStream_FullMethodName = "/gossip_rpc.Gossip/MessageStream"
	Gossip_AckStream_FullMethodName     = "/gossip_rpc.Gossip/AckStream"
	Gossip_Stream_FullMethodName        = "/gossip_rpc.Gossip/Stream"
)

// GossipClient is the client API for Gossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GossipClient interface {
	// 解耦模式
	MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipMessage, GossipMessage], error)
	AckStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipACK, GossipACK], error)
	// 双向流模式
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipMessage, GossipACK], error)
}

type gossipClient struct {
	cc grpc.ClientConnInterface
}

func NewGossipClient(cc grpc.ClientConnInterface) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipMessage, GossipMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gossip_ServiceDesc.Streams[0], Gossip_MessageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GossipMessage, GossipMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_MessageStreamClient = grpc.BidiStreamingClient[GossipMessage, GossipMessage]

func (c *gossipClient) AckStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipACK, GossipACK], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gossip_ServiceDesc.Streams[1], Gossip_AckStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GossipACK, GossipACK]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_AckStreamClient = grpc.BidiStreamingClient[GossipACK, GossipACK]

func (c *gossipClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipMessage, GossipACK], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Gossip_ServiceDesc.Streams[2], Gossip_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GossipMessage, GossipACK]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_StreamClient = grpc.BidiStreamingClient[GossipMessage, GossipACK]

// GossipServer is the server API for Gossip service.
// All implementations must embed UnimplementedGossipServer
// for forward compatibility.
type GossipServer interface {
	// 解耦模式
	MessageStream(grpc.BidiStreamingServer[GossipMessage, GossipMessage]) error
	AckStream(grpc.BidiStreamingServer[GossipACK, GossipACK]) error
	// 双向流模式
	Stream(grpc.BidiStreamingServer[GossipMessage, GossipACK]) error
	mustEmbedUnimplementedGossipServer()
}

// UnimplementedGossipServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGossipServer struct{}

func (UnimplementedGossipServer) MessageStream(grpc.BidiStreamingServer[GossipMessage, GossipMessage]) error {
	return status.Error(codes.Unimplemented, "method MessageStream not implemented")
}
func (UnimplementedGossipServer) AckStream(grpc.BidiStreamingServer[GossipACK, GossipACK]) error {
	return status.Error(codes.Unimplemented, "method AckStream not implemented")
}
func (UnimplementedGossipServer) Stream(grpc.BidiStreamingServer[GossipMessage, GossipACK]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGossipServer) mustEmbedUnimplementedGossipServer() {}
func (UnimplementedGossipServer) testEmbeddedByValue()                {}

// UnsafeGossipServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GossipServer will
// result in compilation errors.
type UnsafeGossipServer interface {
	mustEmbedUnimplementedGossipServer()
}

func RegisterGossipServer(s grpc.ServiceRegistrar, srv GossipServer) {
	// If the following call panics, it indicates UnimplementedGossipServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gossip_ServiceDesc, srv)
}

func _Gossip_MessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GossipServer).MessageStream(&grpc.GenericServerStream[GossipMessage, GossipMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_MessageStreamServer = grpc.BidiStreamingServer[GossipMessage, GossipMessage]

func _Gossip_AckStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GossipServer).AckStream(&grpc.GenericServerStream[GossipACK, GossipACK]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_AckStreamServer = grpc.BidiStreamingServer[GossipACK, GossipACK]

func _Gossip_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GossipServer).Stream(&grpc.GenericServerStream[GossipMessage, GossipACK]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Gossip_StreamServer = grpc.BidiStreamingServer[GossipMessage, GossipACK]

// Gossip_ServiceDesc is the grpc.ServiceDesc for Gossip service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gossip_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gossip_rpc.Gossip",
	HandlerType: (*GossipServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageStream",
			Handler:       _Gossip_MessageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AckStream",
			Handler:       _Gossip_AckStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Stream",
			Handler:       _Gossip_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gossip_rpc.proto",
}
