// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: proto/gossip_rpc.proto

package gossip_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GossipMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	FromHash      string                 `protobuf:"bytes,2,opt,name=FromHash,proto3" json:"FromHash,omitempty"`
	PayLoad       []byte                 `protobuf:"bytes,3,opt,name=PayLoad,proto3" json:"PayLoad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_proto_gossip_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_proto_gossip_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GossipMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GossipMessage) GetFromHash() string {
	if x != nil {
		return x.FromHash
	}
	return ""
}

func (x *GossipMessage) GetPayLoad() []byte {
	if x != nil {
		return x.PayLoad
	}
	return nil
}

type GossipACK struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	FromHash      string                 `protobuf:"bytes,2,opt,name=FromHash,proto3" json:"FromHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipACK) Reset() {
	*x = GossipACK{}
	mi := &file_proto_gossip_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipACK) ProtoMessage() {}

func (x *GossipACK) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipACK.ProtoReflect.Descriptor instead.
func (*GossipACK) Descriptor() ([]byte, []int) {
	return file_proto_gossip_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GossipACK) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GossipACK) GetFromHash() string {
	if x != nil {
		return x.FromHash
	}
	return ""
}

var File_proto_gossip_rpc_proto protoreflect.FileDescriptor

const file_proto_gossip_rpc_proto_rawDesc = "" +
	"\n" +
	"\x16proto/gossip_rpc.proto\x12\n" +
	"gossip_rpc\"Y\n" +
	"\rGossipMessage\x12\x12\n" +
	"\x04Hash\x18\x01 \x01(\tR\x04Hash\x12\x1a\n" +
	"\bFromHash\x18\x02 \x01(\tR\bFromHash\x12\x18\n" +
	"\aPayLoad\x18\x03 \x01(\fR\aPayLoad\";\n" +
	"\tGossipACK\x12\x12\n" +
	"\x04Hash\x18\x01 \x01(\tR\x04Hash\x12\x1a\n" +
	"\bFromHash\x18\x02 \x01(\tR\bFromHash2P\n" +
	"\x06Gossip\x12F\n" +
	"\x12PutMessageToClient\x12\x19.gossip_rpc.GossipMessage\x1a\x15.gossip_rpc.GossipACKB\x19Z\x17Gossip/proto;gossip_rpcb\x06proto3"

var (
	file_proto_gossip_rpc_proto_rawDescOnce sync.Once
	file_proto_gossip_rpc_proto_rawDescData []byte
)

func file_proto_gossip_rpc_proto_rawDescGZIP() []byte {
	file_proto_gossip_rpc_proto_rawDescOnce.Do(func() {
		file_proto_gossip_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gossip_rpc_proto_rawDesc), len(file_proto_gossip_rpc_proto_rawDesc)))
	})
	return file_proto_gossip_rpc_proto_rawDescData
}

var file_proto_gossip_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gossip_rpc_proto_goTypes = []any{
	(*GossipMessage)(nil), // 0: gossip_rpc.GossipMessage
	(*GossipACK)(nil),     // 1: gossip_rpc.GossipACK
}
var file_proto_gossip_rpc_proto_depIdxs = []int32{
	0, // 0: gossip_rpc.Gossip.PutMessageToClient:input_type -> gossip_rpc.GossipMessage
	1, // 1: gossip_rpc.Gossip.PutMessageToClient:output_type -> gossip_rpc.GossipACK
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gossip_rpc_proto_init() }
func file_proto_gossip_rpc_proto_init() {
	if File_proto_gossip_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gossip_rpc_proto_rawDesc), len(file_proto_gossip_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gossip_rpc_proto_goTypes,
		DependencyIndexes: file_proto_gossip_rpc_proto_depIdxs,
		MessageInfos:      file_proto_gossip_rpc_proto_msgTypes,
	}.Build()
	File_proto_gossip_rpc_proto = out.File
	file_proto_gossip_rpc_proto_goTypes = nil
	file_proto_gossip_rpc_proto_depIdxs = nil
}
